############################
## CHANGE THESE
############################

baseURL: "https://haifengrein.github.io/myblog"
title: myblog

############################
## MISC
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "en-us"
enableRobotsTXT: true
