############################
## CHANGE THESE
############################

baseURL: "https://haifenghou.com/"
title: Blog
canonifyURLs: true
relativeURLs: true

############################
## MISC
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "en-us"
enableRobotsTXT: true
